// Code generated by MockGen. DO NOT EDIT.
// Source: product.go

// Package mocks is a generated GoMock package.
package mocks

import (
	context "context"
	reflect "reflect"

	entity "github.com/EM-Stawberry/Stawberry/internal/domain/entity"
	gomock "github.com/golang/mock/gomock"
)

// MockRepository is a mock of Repository interface.
type MockRepository struct {
	ctrl     *gomock.Controller
	recorder *MockRepositoryMockRecorder
}

// MockRepositoryMockRecorder is the mock recorder for MockRepository.
type MockRepositoryMockRecorder struct {
	mock *MockRepository
}

// NewMockRepository creates a new mock instance.
func NewMockRepository(ctrl *gomock.Controller) *MockRepository {
	mock := &MockRepository{ctrl: ctrl}
	mock.recorder = &MockRepositoryMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockRepository) EXPECT() *MockRepositoryMockRecorder {
	return m.recorder
}

// GetAttributesByID mocks base method.
func (m *MockRepository) GetAttributesByID(ctx context.Context, productID string) (map[string]interface{}, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetAttributesByID", ctx, productID)
	ret0, _ := ret[0].(map[string]interface{})
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetAttributesByID indicates an expected call of GetAttributesByID.
func (mr *MockRepositoryMockRecorder) GetAttributesByID(ctx, productID interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetAttributesByID", reflect.TypeOf((*MockRepository)(nil).GetAttributesByID), ctx, productID)
}

// GetAverageRatingByProductID mocks base method.
func (m *MockRepository) GetAverageRatingByProductID(ctx context.Context, productID int) (float64, int, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetAverageRatingByProductID", ctx, productID)
	ret0, _ := ret[0].(float64)
	ret1, _ := ret[1].(int)
	ret2, _ := ret[2].(error)
	return ret0, ret1, ret2
}

// GetAverageRatingByProductID indicates an expected call of GetAverageRatingByProductID.
func (mr *MockRepositoryMockRecorder) GetAverageRatingByProductID(ctx, productID interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetAverageRatingByProductID", reflect.TypeOf((*MockRepository)(nil).GetAverageRatingByProductID), ctx, productID)
}

// GetPriceRangeByProductID mocks base method.
func (m *MockRepository) GetPriceRangeByProductID(ctx context.Context, productID int) (float64, float64, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetPriceRangeByProductID", ctx, productID)
	ret0, _ := ret[0].(float64)
	ret1, _ := ret[1].(float64)
	ret2, _ := ret[2].(error)
	return ret0, ret1, ret2
}

// GetPriceRangeByProductID indicates an expected call of GetPriceRangeByProductID.
func (mr *MockRepositoryMockRecorder) GetPriceRangeByProductID(ctx, productID interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetPriceRangeByProductID", reflect.TypeOf((*MockRepository)(nil).GetPriceRangeByProductID), ctx, productID)
}

// GetProductByID mocks base method.
func (m *MockRepository) GetProductByID(ctx context.Context, id string) (entity.Product, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetProductByID", ctx, id)
	ret0, _ := ret[0].(entity.Product)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetProductByID indicates an expected call of GetProductByID.
func (mr *MockRepositoryMockRecorder) GetProductByID(ctx, id interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetProductByID", reflect.TypeOf((*MockRepository)(nil).GetProductByID), ctx, id)
}

// SelectProducts mocks base method.
func (m *MockRepository) SelectProducts(ctx context.Context, offset, limit int) ([]entity.Product, int, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "SelectProducts", ctx, offset, limit)
	ret0, _ := ret[0].([]entity.Product)
	ret1, _ := ret[1].(int)
	ret2, _ := ret[2].(error)
	return ret0, ret1, ret2
}

// SelectProducts indicates an expected call of SelectProducts.
func (mr *MockRepositoryMockRecorder) SelectProducts(ctx, offset, limit interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "SelectProducts", reflect.TypeOf((*MockRepository)(nil).SelectProducts), ctx, offset, limit)
}

// SelectProductsByFilters mocks base method.
func (m *MockRepository) SelectProductsByFilters(ctx context.Context, categoryID int, filters map[string]interface{}, offset, limit int) ([]entity.Product, int, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "SelectProductsByFilters", ctx, categoryID, filters, offset, limit)
	ret0, _ := ret[0].([]entity.Product)
	ret1, _ := ret[1].(int)
	ret2, _ := ret[2].(error)
	return ret0, ret1, ret2
}

// SelectProductsByFilters indicates an expected call of SelectProductsByFilters.
func (mr *MockRepositoryMockRecorder) SelectProductsByFilters(ctx, categoryID, filters, offset, limit interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "SelectProductsByFilters", reflect.TypeOf((*MockRepository)(nil).SelectProductsByFilters), ctx, categoryID, filters, offset, limit)
}

// SelectProductsByName mocks base method.
func (m *MockRepository) SelectProductsByName(ctx context.Context, name string, offset, limit int) ([]entity.Product, int, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "SelectProductsByName", ctx, name, offset, limit)
	ret0, _ := ret[0].([]entity.Product)
	ret1, _ := ret[1].(int)
	ret2, _ := ret[2].(error)
	return ret0, ret1, ret2
}

// SelectProductsByName indicates an expected call of SelectProductsByName.
func (mr *MockRepositoryMockRecorder) SelectProductsByName(ctx, name, offset, limit interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "SelectProductsByName", reflect.TypeOf((*MockRepository)(nil).SelectProductsByName), ctx, name, offset, limit)
}

// SelectShopProducts mocks base method.
func (m *MockRepository) SelectShopProducts(ctx context.Context, shopID, offset, limit int) ([]entity.Product, int, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "SelectShopProducts", ctx, shopID, offset, limit)
	ret0, _ := ret[0].([]entity.Product)
	ret1, _ := ret[1].(int)
	ret2, _ := ret[2].(error)
	return ret0, ret1, ret2
}

// SelectShopProducts indicates an expected call of SelectShopProducts.
func (mr *MockRepositoryMockRecorder) SelectShopProducts(ctx, shopID, offset, limit interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "SelectShopProducts", reflect.TypeOf((*MockRepository)(nil).SelectShopProducts), ctx, shopID, offset, limit)
}
