service: stawberry
image: stawberry
servers:
  web:
    - orb

proxy:
  app_port: 8080
  healthcheck:
    interval: 3
    path: /health
    timeout: 3
#   ssl: true
#   host: app.example.com

registry:
  server: registry.orb.local
  username:
    - KAMAL_REGISTRY_PASSWORD
  password:
    - KAMAL_REGISTRY_PASSWORD

builder:
  arch: amd64
  dockerfile: deploy/Dockerfile

env:
  clear:
    DB_HOST: stawberry-db
    DB_USER: postgres
    DB_NAME: price_negotiation
    DB_PORT: 5432
    DB_MAX_OPEN_CONNS: 4
    DB_MAX_IDLE_CONNS: 2
    SERVER_PORT: 8080
    TOKEN_ACCESS_DURATION: 15m
    TOKEN_REFRESH_DURATION: 24h
    ENVIRONMENT: production
  secret:
    - DB_PASSWORD
    - TOKEN_SECRET

ssh:
  user: prepin

accessories:
  db:
    image: postgres:17
    host: orb
    env:
      clear:
        POSTGRES_USER: postgres
        POSTGRES_DB: price_negotiation
      secret:
        - POSTGRES_PASSWORD:STAWBERRY_DB_PASSWORD
    directories:
      - data:/var/lib/postgresql/data
