name: Deploy to VPS

on:
  push:
    branches:
      - master
      - deployment

jobs:
  build-and-push:
    runs-on: ubuntu-latest
    permissions:
      packages: write
      contents: read

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Log in to GHCR
        run: echo "${{ secrets.GITHUB_TOKEN }}" | docker login ghcr.io -u ${{ github.actor }} --password-stdin

      - name: Build and Push Image
        run: |
          docker build -t ghcr.io/em-stawberry/stawberry:latest -f deploy/Dockerfile .
          docker push ghcr.io/em-stawberry/stawberry:latest

  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Configure SSH
        uses: webfactory/ssh-agent@v0.7.0
        with:
          ssh-private-key: ${{ secrets.VPS_PRIVATE_KEY }}

      - name: Deploy to VPS
        run: |
          ssh -o StrictHostKeyChecking=no ${{ secrets.VPS_USER }}@${{ secrets.VPS_HOST }} "
            cd /var/www/stawberry/Stawberry &&
            git pull origin deployment &&
            docker compose -f deploy/docker-compose.prod.yml down &&
            docker compose --env-file ./.env -f deploy/docker-compose.prod.yml up -d
          "
