name: Go
on:
  push:
    branches: ["master"]
  pull_request:
    branches: ["master"]
jobs:
  golang-ci:
    name: lint
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-go@v5
        with:
          go-version: "1.23"
      - name: Lint
        uses: golangci/golangci-lint-action@v8
        with:
          version: v2.1.6
          args: -c .golangci.yaml
